package aesx

import (
	"strings"
	"testing"
)

// Interop vectors generated by tools/javaref/CryptoUtil.java (Java 8,
// AES/GCM/NoPadding, GCMParameterSpec(128, ivBytes), UTF-8 key/iv, base64).
// GCM is deterministic for a fixed key/iv/plaintext, so Go output must match
// the Java output byte-for-byte.
var javaVectors = []struct {
	key, iv, plaintext, ciphertext string
}{
	{"8888NOAH8888NOAH", "0CoJyw8Um6QW8jux", "hello world", "jOPZ59WMMMr7kOnC/EfCRjAoeSf4DBaL/RNr"},
	{"0123456789abcdef0123456789abcdef", "0123456789abcdef", "AK=test123/SecretKey/\u00e0 b c", "KdRIjYDP0KOh68lmYrH1JDaPe5arlgD4Fcc4jMPupUL6keu0HS1rSYVTbA=="},
	{"abcdef0123456789abcdef01", "0123456789abcdef", "LTAI5t-test-OSS-SK", "vMRGczGOwnnyu31EU0mtqBToqxEyevBxB/SfapG8MhaZNg=="},
}

func TestInteropWithJavaVectors(t *testing.T) {
	for _, v := range javaVectors {
		gotEnc, err := Encrypt(v.key, v.iv, v.plaintext)
		if err != nil {
			t.Fatalf("Encrypt(%q): %v", v.key, err)
		}
		if gotEnc != v.ciphertext {
			t.Errorf("Go encrypt mismatch: got %q want %q", gotEnc, v.ciphertext)
		}
		gotDec, err := Decrypt(v.key, v.iv, v.ciphertext)
		if err != nil {
			t.Fatalf("Decrypt(%q): %v", v.ciphertext, err)
		}
		if gotDec != v.plaintext {
			t.Errorf("Go decrypt mismatch: got %q want %q", gotDec, v.plaintext)
		}
	}
}

func TestRoundTrip(t *testing.T) {
	key := "8888NOAH8888NOAH"
	iv := "0CoJyw8Um6QW8jux"
	cases := []string{"", "a", "hello world", "中文值 / \u00e0 b c", strings.Repeat("x", 1024)}
	for _, pt := range cases {
		ct, err := Encrypt(key, iv, pt)
		if err != nil {
			t.Fatalf("Encrypt: %v", err)
		}
		got, err := Decrypt(key, iv, ct)
		if err != nil {
			t.Fatalf("Decrypt: %v", err)
		}
		if got != pt {
			t.Errorf("round trip mismatch: got %q want %q", got, pt)
		}
	}
}

func TestKeyLengthValidation(t *testing.T) {
	iv := "0123456789abcdef"
	for _, k := range []string{"", "short", "12345678901234567890", "1234567890123456789012345678901234"} {
		if _, err := Encrypt(k, iv, "x"); err == nil {
			t.Errorf("Encrypt with %d-byte key should fail", len([]byte(k)))
		}
	}
}

func TestWrongKeyFails(t *testing.T) {
	ct, err := Encrypt("8888NOAH8888NOAH", "0CoJyw8Um6QW8jux", "secret")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Decrypt("8888NOAH8888NOAH2", "0CoJyw8Um6QW8jux", ct); err == nil {
		t.Error("decrypt with wrong key should fail")
	}
	if _, err := Decrypt("8888NOAH8888NOAH", "0CoJyw8Um6QW8jux1", ct); err == nil {
		t.Error("decrypt with wrong iv should fail")
	}
	if _, err := Decrypt("8888NOAH8888NOAH", "0CoJyw8Um6QW8jux", "not-base64!!"); err == nil {
		t.Error("decrypt with invalid base64 should fail")
	}
}
